cameras:
  cam1:
    # id: 0
    id: "rtsp://admin:L200461B@192.168.0.182:554/cam/realmonitor?channel=1&subtype=0"
    name: "Camera 1"
    calibration_file: "../calib/cam1_calibration.json"
    position: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    resolution: [1920, 1080]
    
  cam2:
    # id: 1
    id: "rtsp://admin:L2574467@192.168.0.151:554/cam/realmonitor?channel=1&subtype=0"
    name: "Camera 2"
    calibration_file: "../calib/cam2_calibration.json"
    position: [5.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0]
    resolution: [1920, 1080]
    
  # cam3:
  #   id: 2
  #   name: "Camera 3"
  #   calibration_file: "../calib/cam3_calibration.json"
  #   position: [2.5, 5.0, 0.0]
  #   rotation: [0.0, 0.0, 0.0]
  #   resolution: [1920, 1080]

detection:
  confidence_threshold: 0.5
  nms_threshold: 0.4
  
localization:
  min_cameras: 2
  max_reprojection_error: 5.0
  triangulation_method: "DLT"
